export const forumConfig = Object.freeze({
  primaryOrigin: 'https://akatsukigood.forum.cool',
  news: {
    apiUrl: 'https://akatsukigood.forum.cool/api.php',
    topicId: 86,
    limit: 5,
    maxCharacters: 600,
    timeout: 12_000,
  },
  editor: {
    maxDiceCount: 9,
    defaultDiceCount: 1,
    maxDiceSides: 100,
    defaultDiceSides: 10,
    colors: [
      'thistle',
      'yellowgreen',
      'lightblue',
      'lightpink',
      'palegoldenrod',
      'steelblue',
      'orange',
      'forestgreen',
      'firebrick',
      'lightsteelblue',
      'sienna',
      'darkseagreen',
      'saddlebrown',
      'mediumpurple',
      'tan',
      'dodgerblue',
      '#c46f33',
      '#377e22',
      '#808080',
      '#ea3323',
    ],
  },
  posts: {
    defaultAvatar: 'https://forumstatic.ru/files/001a/12/f3/25830.jpg',
  },
  profile: {
    lockedGroupIds: [6],
  },
  radar: {
    maxValue: 10,
    size: 500,
    radius: 200,
    rings: 10,
  },
  mutualPromotion: {
    allowedGroupIds: [1, 2, 5, 6],
    topicPattern: /Ваша реклама/i,
    images: [
      'https://upforme.ru/uploads/001a/12/f3/2/699857.webp',
      'https://upforme.ru/uploads/001a/12/f3/2/517200.webp',
      'https://upforme.ru/uploads/001a/12/f3/67/709559.webp',
    ],
  },
})
